"""Replaceable ports for future telemetry; MVP observes only Gamini video."""
from typing import Protocol
from backend.courier.models import Action, CourierConfig


class PerceptionActions(Protocol):
    async def capture(self, config: CourierConfig) -> bytes: ...
    async def execute(self, actions: list[Action], config: CourierConfig): ...
    async def release(self): ...
    def interrupt(self): ...
    def arm(self): ...


class Model(Protocol):
    async def ask(self, schema, phase: str, context: dict, config: CourierConfig,
                  video: bytes | None = None): ...
